var data = [
    // Ferocity
    [
        {
            index: 1,
            name: "Fury",
            tier: 0,
            ranks: 5,
            desc: "+#% Attack Speed",
            rankInfo: [0.8, 1.6, 2.4, 3.2, 4.0],
        },
        {
            index: 3,
            name: "Sorcery",
            tier: 0,
            ranks: 5,
            desc: "+#% increased Ability and Spell damage",
            rankInfo: [0.4, 0.8, 1.2, 1.6, 2.0],
        },
        {
            index: 5,
            name: "Double-Edged Sword",
            tier: 1,
            ranks: 1,
            desc: "Deal an additional 3% damage, take an additional 1.5% damage",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Feast",
            tier: 1,
            ranks: 1,
            desc: "Killing a unit restores 20 Health (30 second cooldown)",
            rankInfo: [],
        },
        {
            index: 7,
            name: "Expose Weakness",
            tier: 1,
            ranks: 1,
            desc: "Damaging enemy champions causes them to take 3% more damage from your allies",
            rankInfo: [],
        },        
        {
            index: 9,
            name: "Vampirism",
            tier: 2,
            ranks: 5,
            desc: "+#% Lifesteal and Spell Vamp",
            rankInfo: [0.4, 0.8, 1.2, 1.6, 2.0],
        },
        {
            index: 11,
            name: "Natural Talent",
            tier: 2,
            ranks: 5,
            desc: "# Attack Damage and # Ability Power at level 18 (# + # per level Attack Damage and # + # per level Ability Power)",
            rankInfo: [2, 4, 6, 8, 10],
            rankInfo2: [3, 6, 9, 12, 15],
            rankInfo3: [.4, .8, 1.2, 1.6, 2],
            perLevel: [.09, .18, .27, .36, .44],
            rankInfo4: [.6, 1.2, 1.8, 2.4, 3],
            perLevel2: [.13, .27, .4, .53, .67],
        },
        {
            index: 13,
            name: "Bounty Hunter",
            tier: 3,
            ranks: 1,
            desc: "You deal 1% increased damage for each unique enemy champion you kill.",
            rankInfo: [],
        },
        {
            index: 14,
            name: "Oppressor",
            tier: 3,
            ranks: 1,
            desc: "You deal 2.5% increased damage to targets with impaired movement (slow, stun, snare, taunt, etc.)",
            rankInfo: [],
        },
        {
            index: 17,
            name: "Battering Blows",
            tier: 4,
            ranks: 5,
            desc: "+#% Armor Penetration",
            rankInfo: [1.4, 2.8, 4.2, 5.6, 7],
        },
        {
            index: 19,
            name: "Piercing Thoughts",
            tier: 4,
            ranks: 5,
            desc: "+#% Magic Penetration",
            rankInfo: [1.4, 2.8, 4.2, 5.6, 7],
        },
        {
            index: 21,
            name: "Warlord's Bloodlust",
            tier: 5,
            ranks: 1,
            desc: "Gain increasingly more Life Steal based on your missing health against champions (up to 20%). Against minions gain 50% benefit (25% for ranged champions).",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Fervor of Battle",
            tier: 5,
            ranks: 1,
            desc: "Your basic attacks and spells grant you a stack of Fervor for 6 seconds (max 8 stacks). Each stack of Fervor adds 1-14 bonus physical damage to your basic attacks against champions, based on your level.",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Deathfire Touch",
            tier: 5,
            ranks: 1,
            desc: "Your damaging abilities cause enemy champions to take 8 + 60% of your Bonus Attack Damage and 25% of your Ability Power in Magic damage over 4 seconds (Area of effect and damage over time abilities apply half of this damage over 2 / 1 seconds respectively instead).",
            rankInfo: [],
        },
    ],
    // Cunning
    [
        {
            index: 1,
            name: "Wanderer",
            tier: 0,
            ranks: 5,
            desc: "+#% Movement Speed out of Combat",
            rankInfo: [0.6, 1.2, 1.8, 2.4, 3],
        },
        {
            index: 3,
            name: "Savagery",
            tier: 0,
            ranks: 5,
            desc: "Basic attacks and single target spells deal # bonus damage to minions and monsters",
            rankInfo: [1, 2, 3, 4, 5],
        },
        {
            index: 5,
            name: "Runic Affinity",
            tier: 1,
            ranks: 1,
            desc: "Buffs granted by jungle monsters last 15% longer, including Epic Monsters and River Shrine.",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Secret Stash",
            tier: 1,
            ranks: 1,
            desc: "Your potions, flasks, and elixirs last 10% longer. Additionally, your potions are replaced with biscuits that restore 15 Health and Mana instantly upon consumption.",
            rankInfo: [],
        },
        {
            index: 7,
            name: "Assassin",
            tier: 1,
            ranks: 1,
            desc: "Deal 2% increased damage to champions when no allied champions are nearby",
            rankInfo: [],
        },
        {
            index: 9,
            name: "Merciless",
            tier: 2,
            ranks: 5,
            desc: "Deal #% increased damage to champions below 40% Health.",
            rankInfo: [1, 2, 3, 4, 5],
        },
        {
            index: 11,
            name: "Meditation",
            tier: 2,
            ranks: 5,
            desc: "Once every 5 seconds, regenerate #% of your missing Mana.",
            rankInfo: [0.3, 0.6, 0.9, 1.2, 1.5],
        },
        {
            index: 13,
            name: "Bandit",
            tier: 3,
            ranks: 1,
            desc: "Gain 1 gold for each nearby minions killed by allied champions. Gain an additional 3 gold (or 10 if you're melee) when hitting an enemy champion with a basic attack (5 seconds cooldown).",
            rankInfo: [],
        },
        {
            index: 14,
            name: "Dangerous Game",
            tier: 3,
            ranks: 1,
            desc: "Champion kills and assists restore 5% of your missing Health and Mana.",
            rankInfo: [],
        },
        {
            index: 17,
            name: "Precision",
            tier: 4,
            ranks: 5,
            desc: "Gain # + # per level Armor and Magic Penetration",
            rankInfo: [0.6, 1.2, 1.8, 2.4, 3.0],
            rankInfo2: [0.06, 0.12, 0.18, 0.24, 0.3],
        },
        {
            index: 19,
            name: "Intelligence",
            tier: 4,
            ranks: 5,
            desc: "Your Cooldown Reduction cap is increased by #%, gain #% Cooldown Reduction.",
            rankInfo: [1, 2, 3, 4, 5],
            rankInfo2: [1, 2, 3, 4, 5],
        },
        {
            index: 21,
            name: "Stormraider's Surge",
            tier: 5,
            ranks: 1,
            desc: "Dealing 30% of a champion's max Health within 2.5 seconds grants you 40% Movement Speed and 75% Slow Resistance for 3 seconds (10 second cooldown).",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Thunderlord's Decree",
            tier: 5,
            ranks: 1,
            desc: "Your 3rd attack or spell on an enemy champion shocks the area around them, dealing 10 damage per level plus 30% of your Bonus Attack Damage and 10% of your Ability Power as Magic damage to enemies in the area (25-15 second cooldown, based on level).",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Windspeaker's Blessing",
            tier: 5,
            ranks: 1,
            desc: "Your heals and shields are 10% stronger. Additionally, your shields and heals increase your target's armor by 5-22 (based on level) for 3 seconds (half of that for magic resistance) when used on an ally other than yourself.",
            rankInfo: [],
        },
    ],
        // Resolve
    [
        {
            index: 1,
            name: "Recovery",
            tier: 0,
            ranks: 5,
            desc: "+# Health Regen per 5 seconds",
            rankInfo: [0.4, 0.8, 1.2, 1.6, 2.0],
        },
        {
            index: 3,
            name: "Unyielding",
            tier: 0,
            ranks: 5,
            desc: "+#% Bonus Armor and Magic Resist",
            rankInfo: [1, 2, 3, 4, 5],
        },
        {
            index: 5,
            name: "Explorer",
            tier: 1,
            ranks: 1,
            desc: "+15 Movement Speed in Brush and River",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Tough Skin",
            tier: 1,
            ranks: 1,
            desc: "You take 2 less damage from Champion and Monster basic attacks.",
            rankInfo: [],
        },
        {
            index: 9,
            name: "Runic Armor",
            tier: 2,
            ranks: 5,
            desc: "+#% bonus to all shields and healing on you (includes lifesteal and regeneration)",
            rankInfo: [1.6, 3.2, 4.8, 6.4, 8],
        },
        {
            index: 11,
            name: "Veteran's Scars",
            tier: 2,
            ranks: 5,
            desc: "+# Total Health",
            rankInfo: [10, 20, 30, 40, 50],
        },
        {
            index: 13,
            name: "Insight",
            tier: 3,
            ranks: 1,
            desc: "Your summoner spells have 15% reduced cooldown.",
            rankInfo: [],
        },
        {
            index: 14,
            name: "Perseverance",
            tier: 3,
            ranks: 1,
            desc: "+50% Health Regen, increased to +200% when below 25% Health",
            rankInfo: [],
        },
        {
            index: 17,
            name: "Swiftness",
            tier: 4,
            ranks: 5,
            desc: "+#% Tenacity and Slow Resist",
            rankInfo: [3, 6, 9, 12, 15],
        },
        {
            index: 19,
            name: "Legendary Guardian",
            tier: 4,
            ranks: 5,
            desc: "+# Armor and Magic Resist for each nearby enemy champion",
            rankInfo: [0.6, 1.2, 1.8, 2.4, 3],
        },
        {
            index: 21,
            name: "Grasp of the Undying",
            tier: 5,
            ranks: 1,
            desc: "Every 4 seconds in combat your next attack against an enemy champion steals life equal to 3% of your max Health (halved for ranged champions).",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Strength of the Ages",
            tier: 5,
            ranks: 1,
            desc: "Siege minions and large monsters that you or nearby allies kill grant you 20 and 10 permanent Health respectively (300 max). After reaching the max bonus further nearby Siege minion kills restore 6% of your maximum Health.",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Bond of Stone",
            tier: 5,
            ranks: 1,
            desc: "+4% Damage Reduction. 6% of the damage dealt to nearby allies is dealt to you instead (unless you are below 5% Health).",
            rankInfo: [],
        },
    ]
];
